from .base_repo import Base
from .material_repo import MaterialRepo
from .supplier_repo import SupplierRepo
from .client_repo import ClientRepo
from .movement_in_repo import MovementInRepo
from .production_line_repo import ProductionLineRepo
from .product_repo import ProductRepo
from .product_materials_repo import ProductMaterialsRepo
from .movement_out_repo import MovementOutRepo
